# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    tickets_availability_check:
        class: Louvre\BookingBundle\Services\CheckTicketsAvailability
        arguments: ["@doctrine.orm.entity_manager"]

    tickets_availability_validator:
        class: Louvre\BookingBundle\Validator\Constraints\Check1000TicketsLimitValidator
        arguments: ["@tickets_availability_check"]
        tags:
            - { name: validator.constraint_validator }