<?php

namespace Louvre\BookingBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNumberOfBookingsPerDay($dayToBeChecked)
    {
        /*
         * - create query to find the bookings corresponding to a specific booking's visit day
         */
        $queryBuilder = $this->createQueryBuilder("b");
        $queryBuilder->where("b.dateOfVisit = :dateOfVisit")->setParameter("dateOfVisit", $dayToBeChecked);
        $query = $queryBuilder->getQuery();
        $numberOfBookings = $query->getResult();

        return $numberOfBookings;
        // !!! This returns the number or BookingS but does not give the TOTAL number of TicketS!!!
        // USELESS???
        
    }
}
